config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    include KittensHelper

    def index
        @kittens = Kitten.all

        respond_to do |format|
            format.html
            format.xml { render :xml => @kittens }
            format.json { render :json => @kittens }
        end
    end

    def show
        @kitten = Kitten.find(params[:id])

        respond_to do |format|
            format.html
            format.xml { render :xml => @kitten }
            format.json { render :json => @kitten }
        end
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params)
        if @kitten.save
            redirect_to kitten_path(@kitten), notice: "Kitten '#{@kitten.name}' Created!"
          else
            flash.now.notice = "Error in saving"
            render :new
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy
        flash.notice = "Kitten '#{@kitten.name}' Deleted!"
        redirect_to root_path
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])
        if @kitten.update(kitten_params)
            redirect_to kitten_path(@kitten), notice: "Kitten '#{@kitten.name}' Updated!"
          else
            flash.now.notice = "Error in updating"
            render :edit
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten, html: {multipart: true}) do |f| %>
  <ul>
  <% @kitten.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label :softness %><br />
    <%= f.text_field :softness %>
  </p>
  <p>
    <%= f.label :cuteness %><br />
    <%= f.text_field :cuteness %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/kittens/edit.html.erb
<h1>Edit a Kitten</h1>

<%= render partial: 'form' %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<table id="kittens">
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th></th>
        <th></th>
    </tr>
    <% @kittens.each do |kitten| %></td>
        <tr>
            <td><%= kitten.name %></td>
            <td><%= kitten.age %></td>
            <td><%= link_to "delete", kitten_path(kitten), method: :delete, data: {confirm: "Really delete the kitten?"} %></td>
            <td><%= link_to "show", kitten_path(kitten) %></td>
        </tr>
    <% end %>
</table>

<%= link_to "Create a New Kitten", new_kitten_path, class: "new_kitten" %>

app/views/kittens/new.html.erb
<h1>Create a New Kitten</h1>

<%= render partial: 'form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<table id="kittens">
    <tr>
        <th>Age</th>
        <th>Cuteness</th>
        <th>Softness</th>
    </tr>
    <tr>
        <td><%= @kitten.age %></td>
        <td><%= @kitten.cuteness %></td>
        <td><%= @kitten.softness %></td>
    </tr>
</table>

<%= link_to "edit", edit_kitten_path(@kitten) %>
<%= link_to "delete", kitten_path(@kitten), method: :delete, data: {confirm: "Really delete the kitten?"} %>
<%= link_to "<< Back to Kittens List", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>